In [45]:
import pandas as pd

In [46]:
pos = pd.read_csv('/Users/sammynelson/DE  PROJECTS/Capstone-project-2-Fastdeliver_nigeria/fastdeliver_orders.csv')

In [47]:
pos

,order_id,customer_name,pickup_zone,delivery_zone,rider_id,order_date,pickup_time,delivery_time,order_value,delivery_fee,status,payment_method,rider_rating
0,FD-00029,Fatima Bello,Surulere,Ikeja,RDR-023,2026-07-28,13:31,14:45,6137.01,844.62,DELIVERED,card,2.7
1,FD-00257,Ifeanyi Nwachukwu,Yaba,Ojodu,RDR-030,2026-07-28,12:26,13:53,13387.28,508.26,Delivered,transfer,2.7
2,FD-00277,Segun Balogun,Victoria Island,Lekki,RDR-025,2026-07-01,09:21,09:52,13881.6,1183.82,delivered,NaN,3.5
3,FD-00301,Obinna Okonkwo,Surulere,Lekki,RDR-009,2026-07-16,14:31,15:19,"₦10,627.49",1165.94,delivered,transfer,2.8
4,FD-00423,Chidi Okeke,Ojodu,Ikeja,RDR-029,2026-07-23,13:19,NaN,13464.73,327.81,Failed,card,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,FD-00121,Yetunde Akinwande,Ikeja,Lekki,RDR-019,2026-07-22,11:35,NaN,3569.64,676.04,DELIVERED,card,3.6
496,FD-00341,Kelechi Uchenna,Ojodu,Lekki,RDR-016,2026-07-19,15:27,16:29,8316.14,1063.82,Delivered,transfer,4.4
497,FD-00449,Funmilayo Adeyemi,Surulere,Ikeja,RDR-015,2026-07-27,NaN,NaN,3147.62,801.41,Delivered,transfer,3.2
498,FD-00445,Biodun Okafor,Victoria Island,Lekki,RDR-010,2026-07-03,NaN,NaN,7836.38,956.47,DELIVERED,transfer,3.2
499,FD-00131,Chidi Okeke,Lekki,Ojodu,RDR-011,2026-07-02,12:20,13:38,10066.62,348.99,DELIVERED,cash,3.7

In [48]:
# Exploring  Dataframes
print('shape of pos:', pos.shape)
print('---------------------------------------')
print('dtypes of pos:', pos.dtypes)
print('---------------------------------------')
print('info of pos:', pos.info())
print('---------------------------------------')

shape of pos: (500, 13)
---------------------------------------
dtypes of pos: order_id           object
customer_name      object
pickup_zone        object
delivery_zone      object
rider_id           object
order_date         object
pickup_time        object
delivery_time      object
order_value        object
delivery_fee      float64
status             object
payment_method     object
rider_rating      float64
dtype: object
---------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        500 non-null    object
 1   customer_name   500 non-null    object
 2   pickup_zone     500 non-null    object
 3   delivery_zone   500 non-null    object
 4   rider_id        500 non-null    object
 5   order_date      500 non-null    object
 6   pickup_time     368 non-null    object
 7   delivery_time   242 non-null    object
 8   order_value     480 non-null    object
 9   delivery_fee    500 non-null    float64
 10  status          500 non-null    object
 11  payment_method  454 non-null    object
 12  rider_rating    430 non-null    float64
dtypes: float64(2), object(11)
memory usage: 50.9+ KB
info of pos: None
---------------------------------------

In [9]:
# Descrption of the Data(quick summary of the data)
pos.describe()
pos.head(5)

,order_id,customer_name,pickup_zone,delivery_zone,rider_id,order_date,pickup_time,delivery_time,order_value,delivery_fee,status,payment_method,rider_rating
0,FD-00029,Fatima Bello,Surulere,Ikeja,RDR-023,2026-07-28,13:31,14:45,6137.01,844.62,DELIVERED,card,2.7
1,FD-00257,Ifeanyi Nwachukwu,Yaba,Ojodu,RDR-030,2026-07-28,12:26,13:53,13387.28,508.26,Delivered,transfer,2.7
2,FD-00277,Segun Balogun,Victoria Island,Lekki,RDR-025,2026-07-01,09:21,09:52,13881.6,1183.82,delivered,NaN,3.5
3,FD-00301,Obinna Okonkwo,Surulere,Lekki,RDR-009,2026-07-16,14:31,15:19,"₦10,627.49",1165.94,delivered,transfer,2.8
4,FD-00423,Chidi Okeke,Ojodu,Ikeja,RDR-029,2026-07-23,13:19,NaN,13464.73,327.81,Failed,card,4.4

    ### CHECKING  MISSING VALUES

In [49]:
pos.isnull().sum()

order_id            0
customer_name       0
pickup_zone         0
delivery_zone       0
rider_id            0
order_date          0
pickup_time       132
delivery_time     258
order_value        20
delivery_fee        0
status              0
payment_method     46
rider_rating       70
dtype: int64

### CHECKING FOR DUPLICATES

In [50]:
pos.duplicated().sum() # 40 duplicated values in the dataset. We will remove them and create a new dataframe called pos_cleaned

np.int64(40)

### CLEANING DATA

In [51]:
print(f"Shape  of pos before cleaning: {pos.shape}")
print(f" Missing Values:\n{pos[['pickup_time', 'delivery_time', 'order_value', 'payment_method', 'rider_rating']].isnull().sum()}")
print(f" Duplicate Values:{pos.duplicated().sum()}")
print(f" dtype :\n{pos[['order_date', 'pickup_time', 'delivery_time', 'order_value']].dtypes}")
print()

Shape  of pos before cleaning: (500, 13)
 Missing Values:
pickup_time       132
delivery_time     258
order_value        20
payment_method     46
rider_rating       70
dtype: int64
 Duplicate Values:40
 dtype :
order_date       object
pickup_time      object
delivery_time    object
order_value      object
dtype: object

In [56]:
# Check the percentage of missing values
missing_percentage = pos.isnull().mean() * 100
print(missing_percentage)
# If a column is < 5%, go ahead and drop
# pos_df.dropna(subset=['column_name'], inplace=True) pd

order_id           0.0
customer_name      0.0
pickup_zone        0.0
delivery_zone      0.0
rider_id           0.0
order_date         0.0
pickup_time       26.4
delivery_time     51.6
order_value        4.0
delivery_fee       0.0
status             0.0
payment_method     9.2
rider_rating      14.0
dtype: float64

In [57]:
pos_df = pos.copy()

In [58]:
# 1. First convert to datetime - do this BEFORE filling
pos_df['order_date'] = pd.to_datetime(pos_df['order_date'], errors='coerce')
pos_df['pickup_time'] = pd.to_datetime(pos_df['pickup_time'], errors='coerce')
pos_df['delivery_time'] = pd.to_datetime(pos_df['delivery_time'], errors='coerce')
pos_df['order_value'] = pd.to_numeric(pos_df['order_value'], errors='coerce')

# 3. Check dtypes now
print(pos_df[['order_date','pickup_time','delivery_time','order_value']].dtypes)
print(pos_df.isnull().sum())

order_date       datetime64[ns]
pickup_time      datetime64[ns]
delivery_time    datetime64[ns]
order_value             float64
dtype: object
order_id            0
customer_name       0
pickup_zone         0
delivery_zone       0
rider_id            0
order_date          0
pickup_time       132
delivery_time     258
order_value        84
delivery_fee        0
status              0
payment_method     46
rider_rating       70
dtype: int64

/var/folders/x8/q0h5r3zn5897h3jk686j62bc0000gn/T/ipykernel_62521/54896963.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pos_df['pickup_time'] = pd.to_datetime(pos_df['pickup_time'], errors='coerce')
/var/folders/x8/q0h5r3zn5897h3jk686j62bc0000gn/T/ipykernel_62521/54896963.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pos_df['delivery_time'] = pd.to_datetime(pos_df['delivery_time'], errors='coerce')

In [59]:
#fill missing values/blanks with mean for order_value and rider_rating
#.1 Fill numeric columns with mean
pos_df['pickup_time'] = pos_df['pickup_time'].fillna(pos_df['pickup_time'].mean())
pos_df['delivery_time'] = pos_df['delivery_time'].fillna(pos_df['delivery_time'].mean())
pos_df['rider_rating'] = pos_df['rider_rating'].fillna(pos_df['rider_rating'].mean())

#.2 Fill categorical with mode
pos_df['payment_method'] = pos_df['payment_method'].fillna(pos_df['payment_method'].mode()[0])

## Dropping missing values
# For pickup_time & delivery_time - DO NOT FILL WITH MEAN
# Just drop rows where time is missing - best for delivery analysis
#pos_df = pos_df.dropna(subset=['pickup_time', 'delivery_time', 'order_value'])
pos_df = pos_df.dropna(subset=['order_value'])
pos_df.isnull().sum()

order_id          0
customer_name     0
pickup_zone       0
delivery_zone     0
rider_id          0
order_date        0
pickup_time       0
delivery_time     0
order_value       0
delivery_fee      0
status            0
payment_method    0
rider_rating      0
dtype: int64

In [23]:
## Dropping duplicates row
pos_df.drop_duplicates(inplace=True)
pos_df.duplicated().sum()

np.int64(0)

In [24]:
pos_df

,order_id,customer_name,pickup_zone,delivery_zone,rider_id,order_date,pickup_time,delivery_time,order_value,delivery_fee,status,payment_method,rider_rating
0,FD-00029,Fatima Bello,Surulere,Ikeja,RDR-023,2026-07-28,2026-09-02 13:31,2026-09-02 14:45,6137.01,844.62,DELIVERED,card,2.7
1,FD-00257,Ifeanyi Nwachukwu,Yaba,Ojodu,RDR-030,2026-07-28,2026-09-02 12:26,2026-09-02 13:53,13387.28,508.26,Delivered,transfer,2.7
2,FD-00277,Segun Balogun,Victoria Island,Lekki,RDR-025,2026-07-01,2026-09-02 09:21,2026-09-02 09:52,13881.60,1183.82,delivered,cash,3.5
4,FD-00423,Chidi Okeke,Ojodu,Ikeja,RDR-029,2026-07-23,2026-09-02 13:19,2026-09-02 15:17,13464.73,327.81,Failed,card,4.4
5,FD-00132,Babatunde Oluwole,Ikeja,Lekki,RDR-008,2026-07-16,2026-09-02 16:34,2026-09-02 17:31,4232.26,245.72,failed,cash,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,FD-00121,Yetunde Akinwande,Ikeja,Lekki,RDR-019,2026-07-22,2026-09-02 11:35,2026-09-02 15:17,3569.64,676.04,DELIVERED,card,3.6
496,FD-00341,Kelechi Uchenna,Ojodu,Lekki,RDR-016,2026-07-19,2026-09-02 15:27,2026-09-02 16:29,8316.14,1063.82,Delivered,transfer,4.4
497,FD-00449,Funmilayo Adeyemi,Surulere,Ikeja,RDR-015,2026-07-27,2026-09-02 14:26,2026-09-02 15:17,3147.62,801.41,Delivered,transfer,3.2
498,FD-00445,Biodun Okafor,Victoria Island,Lekki,RDR-010,2026-07-03,2026-09-02 14:26,2026-09-02 15:17,7836.38,956.47,DELIVERED,transfer,3.2
499,FD-00131,Chidi Okeke,Lekki,Ojodu,RDR-011,2026-07-02,2026-09-02 12:20,2026-09-02 13:38,10066.62,348.99,DELIVERED,cash,3.7

In [25]:
# Now try - find the zone column
zone_col = [c for c in pos_df.columns if 'zone' in c or 'area' in c or 'location' in c][0]
print(f"Using '{zone_col}' as zone column")

Using 'pickup_zone' as zone column

In [26]:
### At least 2 groupby analyses 
# Groupby 1: Revenue by zone
revenue_by_zone = pos_df.groupby(zone_col)['order_value'].agg(['sum','mean','count']).round(2)
revenue_by_zone = revenue_by_zone.sort_values('sum', ascending=False)
print(revenue_by_zone.head())

                       sum     mean  count
pickup_zone
Victoria Island  623727.70  7996.51     78
Ojodu            567054.47  7875.76     72
Lekki            508771.65  8205.99     62
Surulere         489011.86  8732.35     56
Yaba             464440.60  8148.08     57

In [27]:
# Groupby 2: by rider
rider_col = [c for c in pos_df.columns if 'rider' in c.lower()][0]

rider_performance = pos_df.groupby(rider_col).agg(
    total_orders=('order_id','count'),
    avg_rating=('rider_rating','mean'),
    total_revenue=('order_value','sum')
).round(2).sort_values('total_revenue', ascending=False)

print(rider_performance.head())

          total_orders  avg_rating  total_revenue
rider_id
RDR-026             19        3.53      161945.56
RDR-016             14        3.81      141548.93
RDR-029             14        3.76      140468.21
RDR-020             15        3.55      137028.47
RDR-027             14        3.50      130763.92

In [28]:
# Groupby 3: by payment method
pay_col = [c for c in pos_df.columns if 'payment' in c][0]
payment_analysis = pos_df.groupby(pay_col)['order_value'].mean().round(2)
print(payment_analysis)

payment_method
card        7936.60
cash        8236.71
transfer    7888.51
Name: order_value, dtype: float64

In [18]:
from sqlalchemy import create_engine, text

In [65]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = "Sammynelson061%"  # your real password
encoded_pwd = quote_plus(password)  # becomes 1980Theo%40

engine = create_engine(f"postgresql+psycopg2://postgres:{encoded_pwd}@localhost:5432/Fastdelivery_db")

try:
    with engine.connect() as connection:
        print("Database connection established successfully!")
except Exception as e:
    print("Connection failed:", e)

Database connection established successfully!

416